version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "african-language-assistant"
s3_prefix = "african-language-assistant"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"
image_repositories = []

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "african-language-assistant-prod"
s3_prefix = "african-language-assistant-prod"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod"
image_repositories = []
